
[global]
project_id = "owzerqaududhfwngyqbp"

[connect-google]
verify_jwt = false
allow_public_network_access = true

[google-callback]
verify_jwt = false
allow_public_network_access = true

[vapi-calendar-api]
verify_jwt = false
allow_public_network_access = true

[register-vapi-calendar-tools]
verify_jwt = false
allow_public_network_access = true

[shared_schema]
migrations_dir = "migrations"
