
# project_id is a required field when using verify_jwt
project_id = "owzerqaududhfwngyqbp"
# Don't require authentication for this function since we'll handle it inside
verify_jwt = false
allow_public_network_access = true
